### ISSUE TITLE
Doesn't find partials in the same directory, no recompilation after change of a partial.

### ISSUE THREAD

**Issue by ZeroMax-dev** [jasonsanjose/brackets-sass#95] opened 2015-02-19 20:32 UTC
Using a fresh Brackets 1.1 and brackets-sass 1.0.4-83 on Win8.1 (64-bit) if i import a partial that is in the same directory as the importing file with `@import "partial";` I get an error `File to import not found or unreadable`. My file structure is as follows:

    /
    -> css/main.css
    -> css/main.css.map
    -> img/etc.
    -> scss/_partial.scss
    -> scss/main.scss
    index.html
    .brackets.json

If I add the full absolute path to the scss-directory ("X:/Documents/project/scss/") in the `includePath`-attribute in the `.brackets.json` the partials are being found. But even then, if I change the contents of a partial the change is not detected and the `main.scss` is not recompiled. It is only recompiled if i make a change in the `main.scss`.

**Comment by ofhouse** [comment] 2015-02-22 18:59
I have the same issue.
Found out, that the extension don't recognizes partials correctly instead it handles them as normal InputFiles.
Maybe a result of this [issue](https://github.com/jasonsanjose/brackets-sass/issues/89)?

**Comment by Turqueso** [comment] 2015-02-23 01:22
Had the same problem, tried to uninstall and reinstall, now i can't install it! it keeps installing forever :sob:

**Comment by ofhouse** [comment] 2015-02-23 12:20
Have you set ```includePaths``` in your ```.brackets.json```?

**Comment by Turqueso** [comment] 2015-02-25 00:09
This is my file
```
{
    "sass.enabled": true,
    "path": {
        "scss/main.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../stylesheets",
                "includePaths": [],
                "imagePath": null,
                "sourceComments": false,
                "outputStyle": "nested"
            }
        }
    }
}
```

But this is happening with new projects and project i've been working just fine, don't know what happened since i did not modified them and it is just in windows, on mac it's fine

**Comment by nicolo-ribaudo** [comment] 2015-02-26 16:32
I think it's because your projects are on a drive other than `c:/`

Can you test if in [this branch](https://github.com/nicolo-ribaudo/brackets-sass/tree/issue-95) partials are found?

**Comment by Turqueso** [comment] 2015-02-27 04:09
@nicolo-ribaudo excuse my ignorance, but how can i test the brach? what file(s) should i download

**Comment by nicolo-ribaudo** [comment] 2015-02-27 05:56
1. Uninstall the extension
2. Click on "Install from url" in Extension Manager
3. Write the url of the branch

**Comment by Turqueso** [comment] 2015-02-28 19:50
Is this the url [https://github.com/nicolo-ribaudo/brackets-sass/archive/issue-95.zip](https://github.com/nicolo-ribaudo/brackets-sass/archive/issue-95.zip)? because i get this

![image](https://cloud.githubusercontent.com/assets/4932347/6427773/49153de4-bf48-11e4-8859-5edd76df4640.png)
![image](https://cloud.githubusercontent.com/assets/4932347/6427774/54bf8032-bf48-11e4-8c3c-4c1008469c2e.png)

**Comment by ofhouse** [comment] 2015-02-28 21:10
Yeah, it's the right package but the install fails because Github is not able to include submodules (thirdparty/source-map/) in the zip archive.

Better use ```git clone``` instead if you are familiar with git.

**Comment by jasonsanjose** [comment] 2015-03-02 19:45
Closing as duplicate of #91.

@ZeroMax-dev @Turqueso See comment here https://github.com/jasonsanjose/brackets-sass/issues/91#issuecomment-76795368 to try the latest dev build with a fix.

**Closed by jasonsanjose** 2015-03-02 19:45 UTC
