### ISSUE TITLE
Path issue in Windows

### ISSUE THREAD

**Issue by tijtij** [jasonsanjose/brackets-sass#89] opened 2015-02-01 00:23 UTC
Don't know if this is an issue with the Bourbon example, brackets-sass, or libsass but compiling is broken when the project files are located on my D drive.

This is what `app.css.map` looks like:

```javascript
{
  "version": 3,
  "file": "app.css",
  "sources": [
    "C:/D:/bourbon-example-master/scss/app.scss",
    "C:/D:/bourbon-example-master/bower_components/bourbon/dist/_bourbon.scss",
    "C:/D:/bourbon-example-master/scss/partial.scss",
...
```

Previously reported in issue https://github.com/jasonsanjose/brackets-sass/issues/21#issuecomment-64128971

**Comment by ofhouse** [comment] 2015-02-22 22:30
Same here.
Found out that the issue was caused by this [code](https://github.com/jasonsanjose/brackets-sass/blob/master/node/1.1.4-3/render.js#L83).
Unfortunately I'm not really experienced with Node.js so I don't know how to debug Node.js code to fix that :\
```console.log()``` doesn't work here.

**Comment by nicolo-ribaudo** [comment] 2015-02-25 21:00
Fixed: #99

**Comment by jasonsanjose** [comment] 2015-02-28 01:03
FWIW the path that we get from the source map returned from node-sass will typically look like this:

```
../../../../../../../../../../D:/bourbon-example/scss/partial.scss
```

The bug happens when the input file and some included path are on different drives.

**Comment by jasonsanjose** [comment] 2015-02-28 01:04
Closing. Targeting v2.

**Comment by jasonsanjose** [comment] 2015-03-02 19:22
See test build here https://github.com/jasonsanjose/brackets-sass/pull/100#issuecomment-76787328 with path fixes for both libsass and ruby. Targeting for v2 release.

**Comment by jasonsanjose** [comment] 2015-03-05 00:11
Re-opening since PR #100 hasn't been merged yet.

**Comment by jasonsanjose** [comment] 2015-03-05 00:15
@tijtij there's a test build you can try here https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-105. If you have some time, please let me know if that fixes your problem.

**Comment by tijtij** [comment] 2015-03-05 01:27
@jasonsanjose Works for me on Brackets 1.20-15697.

None of sources paths in *.css.map are using drive letters.

Thanks for the fix.

**Closed** 2015-03-05 01:29 UTC
Labels: fix in progress
